import { ResourcesBalanceCardProps } from 'components/ResourcesBalanceCard/ResourcesBalanceCard'
import { ResourcesTokenCardProps } from 'components/ResourcesTokenCard/ResourcesTokenCard'

export const mockRecourcesBalanceCard: ResourcesBalanceCardProps[] = [
  {
    amount: 3058.23,
    features: ['add funds', 'transfer', 'withdraw funds'],
    resource: 'usdt',
  },
  {
    amount: 15567.55,
    features: ['add funds', 'transfer'],
    resource: 'map',
  },
]

export const mockRecourcesTokenCard: ResourcesTokenCardProps[] = [
  {
    balance: 4176,
    type: 'oxygen',
    collectionCounter: [
      { counterName: 'Total collected', amount: 27284 },
      { counterName: 'Generated by you', amount: 13102 },
      { counterName: 'Received at neighbors', amount: 371 },
      { counterName: 'Received by bonuses', amount: 1 },
    ],
  },
  {
    balance: 0,
    type: 'water',
    collectionCounter: [
      { counterName: 'Total collected', amount: 0 },
      { counterName: 'Generated by you', amount: 0 },
      { counterName: 'Received at neighbors', amount: 0 },
      { counterName: 'Received by bonuses', amount: 0 },
    ],
  },
  {
    balance: 13225,
    type: 'energy',
    collectionCounter: [
      { counterName: 'Total collected', amount: 153587 },
      { counterName: 'Generated by you', amount: 99567 },
      { counterName: 'Received at neighbors', amount: 558 },
      { counterName: 'Received by bonuses', amount: 1600 },
    ],
  },
  {
    balance: 8952,
    type: 'minerals',
    collectionCounter: [
      { counterName: 'Total collected', amount: 53284 },
      { counterName: 'Generated by you', amount: 21458 },
      { counterName: 'Received at neighbors', amount: 2088 },
      { counterName: 'Received by bonuses', amount: 800 },
    ],
  },
]
